### ISSUE TITLE
System boot BIOS self-test error, invalid system time

### ISSUE THREAD

**Issue by github-wang** [caturmahdialfurqon/HP-Elitdesk-800-G4-G5-Hackintosh#1]
![image](https://github.com/caturmahdialfurqon/HP-Elitdesk-800-G4-G5-Hackintosh/assets/5675180/7c4c513c-386b-4996-a87e-f29c00020bf3)

**Comment by caturmahdialfurqon** [comment]
you need RTC patch, if this patch on kernel `__ZN8AppleRTC18setupDateTimeAlarmEPK11RTCDateTime` doesn't work.
try to add patch on ACPI.

- Comment: RTC fix to stop Post Error

- Find: <47017000 70000108>

- Replace: <47017000 70000102>

**Comment by caturmahdialfurqon** [comment]
or you can blacklist permanent on NVRAM.
UUID : 4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102
Key : rtc-blacklist
Data Type : Data
![Screenshot 2024-07-10 at 16 54 02](https://github.com/caturmahdialfurqon/HP-Elitdesk-800-G4-G5-Hackintosh/assets/69003304/02210819-696d-41cb-83fb-adbf5116eaf3)
